import { Rule } from './types'

// Built-in detection rules. Java first (enterprise language).
// Each pattern is a regex string matched against individual lines of source code.
// Snippets sent to AI scoring are capped at 5 lines — no full files leave the system.

export const BUILT_IN_RULES: Rule[] = [
  // ─── JAVA ───────────────────────────────────────────────────────────────────

  {
    id: 'java-rsa-keygen',
    language: 'java',
    pattern: 'KeyPairGenerator\\.getInstance\\s*\\(\\s*["\']RSA["\']',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'RSA key generation is quantum-vulnerable',
    migration: 'Replace with ML-DSA (FIPS 204) for signing or ML-KEM (FIPS 203) for key encapsulation.',
    references: ['NIST FIPS 204', 'NIST FIPS 203'],
  },
  {
    id: 'java-rsa-cipher',
    language: 'java',
    pattern: 'Cipher\\.getInstance\\s*\\(\\s*["\']RSA',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'RSA cipher is quantum-vulnerable',
    migration: 'Replace with ML-KEM (FIPS 203) for key encapsulation. RSA encryption is broadly discouraged even classically.',
    references: ['NIST FIPS 203'],
  },
  {
    id: 'java-ecdh',
    language: 'java',
    pattern: 'KeyAgreement\\.getInstance\\s*\\(\\s*["\']ECDH["\']',
    algorithm: 'ECDH',
    severity: 'HIGH',
    message: 'ECDH key agreement is quantum-vulnerable',
    migration: 'Replace with ML-KEM (FIPS 203) for key encapsulation.',
    references: ['NIST FIPS 203'],
  },
  {
    id: 'java-ecdsa',
    language: 'java',
    pattern: 'KeyPairGenerator\\.getInstance\\s*\\(\\s*["\']EC["\']',
    algorithm: 'ECDSA',
    severity: 'HIGH',
    message: 'EC (ECDSA/ECDH) key generation is quantum-vulnerable',
    migration: 'For signatures: replace with ML-DSA (FIPS 204). For key agreement: replace with ML-KEM (FIPS 203).',
    references: ['NIST FIPS 203', 'NIST FIPS 204'],
  },
  {
    id: 'java-sha1-signature',
    language: 'java',
    pattern: 'Signature\\.getInstance\\s*\\(\\s*["\']SHA1with',
    algorithm: 'SHA-1',
    severity: 'HIGH',
    message: 'SHA-1 signature scheme is broken (classically and quantum)',
    migration: 'Replace with ML-DSA (FIPS 204) or at minimum SHA256withRSA (still classically safe, not quantum-safe).',
    references: ['NIST FIPS 204', 'NIST SP 800-131A'],
  },
  {
    id: 'java-dsa',
    language: 'java',
    pattern: 'KeyPairGenerator\\.getInstance\\s*\\(\\s*["\']DSA["\']',
    algorithm: 'DSA',
    severity: 'HIGH',
    message: 'DSA is quantum-vulnerable',
    migration: 'Replace with ML-DSA (FIPS 204).',
    references: ['NIST FIPS 204'],
  },
  {
    id: 'java-dh',
    language: 'java',
    pattern: 'KeyPairGenerator\\.getInstance\\s*\\(\\s*["\']DH["\']',
    algorithm: 'DH',
    severity: 'HIGH',
    message: 'Diffie-Hellman key exchange is quantum-vulnerable',
    migration: 'Replace with ML-KEM (FIPS 203).',
    references: ['NIST FIPS 203'],
  },
  // Bouncy Castle patterns
  {
    id: 'java-bc-rsa-params',
    language: 'java',
    pattern: 'RSAKeyGenerationParameters|RSAPrivateCrtKeyParameters|RSAKeyParameters',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'Bouncy Castle RSA usage is quantum-vulnerable',
    migration: 'Replace with ML-DSA or ML-KEM from Bouncy Castle\'s PQC module (org.bouncycastle.pqc.crypto).',
    references: ['NIST FIPS 203', 'NIST FIPS 204'],
  },
  {
    id: 'java-bc-ecdh',
    language: 'java',
    pattern: 'ECDHBasicAgreement|ECDHCBasicAgreement',
    algorithm: 'ECDH',
    severity: 'HIGH',
    message: 'Bouncy Castle ECDH usage is quantum-vulnerable',
    migration: 'Replace with KyberKEM from Bouncy Castle PQC module.',
    references: ['NIST FIPS 203'],
  },

  // ─── PYTHON ─────────────────────────────────────────────────────────────────

  {
    id: 'python-rsa-generate',
    language: 'python',
    pattern: 'rsa\\.generate_private_key|RSA\\.generate|generate_private_key.*rsa',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'RSA key generation is quantum-vulnerable',
    migration: 'Replace with ML-DSA or ML-KEM. Use the `pqcrypto` or `liboqs-python` library.',
    references: ['NIST FIPS 203', 'NIST FIPS 204'],
  },
  {
    id: 'python-ec-generate',
    language: 'python',
    pattern: 'ec\\.generate_private_key|ECDH\\(|ECDSA\\(',
    algorithm: 'ECDSA/ECDH',
    severity: 'HIGH',
    message: 'Elliptic curve cryptography is quantum-vulnerable',
    migration: 'For signatures: ML-DSA (FIPS 204). For key agreement: ML-KEM (FIPS 203).',
    references: ['NIST FIPS 203', 'NIST FIPS 204'],
  },
  {
    id: 'python-cryptography-rsa',
    language: 'python',
    pattern: 'from cryptography.*import.*RSA|import rsa\\b',
    algorithm: 'RSA',
    severity: 'MEDIUM',
    message: 'RSA import detected — verify usage is not for long-lived keys',
    migration: 'Audit all uses of this import. Migrate key exchange to ML-KEM, signatures to ML-DSA.',
    references: ['NIST FIPS 203', 'NIST FIPS 204'],
  },
  {
    id: 'python-paramiko-rsa',
    language: 'python',
    pattern: 'paramiko\\.RSAKey|RSAKey\\.generate',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'Paramiko RSA SSH key is quantum-vulnerable',
    migration: 'Migrate SSH to use ML-KEM hybrid mode. OpenSSH 9.0+ supports hybrid ML-KEM/x25519.',
    references: ['NIST FIPS 203', 'OpenSSH 9.0 release notes'],
  },

  // ─── JAVASCRIPT / TYPESCRIPT ────────────────────────────────────────────────

  {
    id: 'js-webcrypto-rsa',
    language: 'any',
    pattern: 'generateKey.*RSA-OAEP|generateKey.*RSASSA-PKCS1|generateKey.*RSA-PSS',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'Web Crypto RSA key generation is quantum-vulnerable',
    migration: 'No native Web Crypto PQC support yet. Use the `liboqs-js` WASM library for ML-KEM/ML-DSA.',
    references: ['NIST FIPS 203', 'NIST FIPS 204'],
  },
  {
    id: 'js-webcrypto-ecdh',
    language: 'any',
    pattern: 'generateKey.*ECDH|generateKey.*ECDSA',
    algorithm: 'ECDH/ECDSA',
    severity: 'HIGH',
    message: 'Web Crypto EC key generation is quantum-vulnerable',
    migration: 'Use `liboqs-js` for ML-KEM (key agreement) or ML-DSA (signatures) until Web Crypto adds PQC.',
    references: ['NIST FIPS 203', 'NIST FIPS 204'],
  },
  {
    id: 'js-node-rsa',
    language: 'any',
    pattern: 'generateKeyPair.*rsa|createSign.*RSA|createVerify.*RSA',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'Node.js RSA usage is quantum-vulnerable',
    migration: 'Replace with ML-DSA for signing or ML-KEM for key encapsulation via `liboqs-node`.',
    references: ['NIST FIPS 203', 'NIST FIPS 204'],
  },
  {
    id: 'js-node-ecdh',
    language: 'any',
    pattern: 'createECDH\\(|generateKeyPair.*ec\\b',
    algorithm: 'ECDH',
    severity: 'HIGH',
    message: 'Node.js ECDH key agreement is quantum-vulnerable',
    migration: 'Replace with ML-KEM via `liboqs-node`.',
    references: ['NIST FIPS 203'],
  },
  {
    id: 'js-jose-rsa',
    language: 'any',
    pattern: 'generateKeyPair.*RS256|RS384|RS512|PS256|PS384|PS512',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'JOSE/JWT RSA signing algorithm is quantum-vulnerable',
    migration: 'Migrate JWT signing to ML-DSA when JOSE PQC standards are finalized (IETF draft in progress).',
    references: ['NIST FIPS 204'],
  },

  // ─── GO ─────────────────────────────────────────────────────────────────────

  {
    id: 'go-rsa-generate',
    language: 'go',
    pattern: 'rsa\\.GenerateKey|rsa\\.GenerateMultiPrimeKey',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'Go RSA key generation is quantum-vulnerable',
    migration: 'Replace with ML-KEM or ML-DSA via `github.com/cloudflare/circl` or `golang.org/x/crypto/mlkem`.',
    references: ['NIST FIPS 203', 'NIST FIPS 204'],
  },
  {
    id: 'go-ecdh',
    language: 'go',
    pattern: 'ecdh\\.P256\\(\\)|ecdh\\.P384\\(\\)|ecdh\\.P521\\(\\)|ecdh\\.X25519\\(\\)',
    algorithm: 'ECDH',
    severity: 'HIGH',
    message: 'Go ECDH key agreement is quantum-vulnerable',
    migration: 'Replace with ML-KEM via `golang.org/x/crypto/mlkem` (added in Go 1.24).',
    references: ['NIST FIPS 203', 'Go 1.24 release notes'],
  },
  {
    id: 'go-ecdsa',
    language: 'go',
    pattern: 'ecdsa\\.GenerateKey|ecdsa\\.Sign|ecdsa\\.Verify',
    algorithm: 'ECDSA',
    severity: 'HIGH',
    message: 'Go ECDSA is quantum-vulnerable',
    migration: 'Replace with ML-DSA via `github.com/cloudflare/circl/sign/mldsa`.',
    references: ['NIST FIPS 204'],
  },
  {
    id: 'go-dsa',
    language: 'go',
    pattern: 'dsa\\.GenerateKey|dsa\\.Sign',
    algorithm: 'DSA',
    severity: 'HIGH',
    message: 'Go DSA is quantum-vulnerable (and deprecated since Go 1.15)',
    migration: 'Replace with ML-DSA via `github.com/cloudflare/circl/sign/mldsa`.',
    references: ['NIST FIPS 204'],
  },
  {
    id: 'go-tls-rsa-cipher',
    language: 'go',
    pattern: 'tls\\.TLS_RSA_WITH|tls\\.TLS_ECDHE_RSA',
    algorithm: 'RSA',
    severity: 'HIGH',
    message: 'TLS cipher suite using RSA is quantum-vulnerable',
    migration: 'Use TLS 1.3 with hybrid ML-KEM. Go\'s `crypto/tls` supports X25519MLKEM768 in Go 1.24.',
    references: ['NIST FIPS 203', 'Go 1.24 release notes'],
  },
]
